### ISSUE TITLE
US02 - Eu como professor quero realizar meu cadastro para realizar o uso da plataforma

### ISSUE THREAD

**Issue by DLBrianPina** [OrcestraGamificacao/Dorime-Docs#2]
- [x] Usar o flask-mongoengine para realizar a conexão com o banco de dados
- [x] Criar o modelo do professor
- [x] Criar as rotas referentes ao cadastro de professor, sem o uso de e-mail
- [x] Criar interface referente ao cadastro
- [x] Usar o padrão BEM e o padrão SMACSS com o SASS para realizar a estilização

A interface web deve seguir [o protótipo de alta fidelidade](https://www.figma.com/file/eIpMAB7lJJA6HyVbzpePVv/Dorime?node-id=4%3A2).

**Comment by IagoTheophilo** [comment]
No protótipo não tem tela de Cadastro de professor. Só tem tela de Login.

**Comment by DLBrianPina** [comment]
🏆 Muito bom!
