### ISSUE TITLE
HOTFIX - Mudança no protótipo da página de enviar treinos

### ISSUE THREAD

**Issue by VitorLamego** [OrcestraGamificacao/Dorime-Docs#25]
- [x] A página onde o professor monta o treino do aluno deve possuir uma seção que ele possa escolher de maneira rápida alguma treino já presente no seu banco de treinos. ( Atributo my_trainings no back ).
- [x] A página deve conter mais informações referente ao treino, como a data que será destinada ao aluno realizar tal treino, assim como uma pontuação escolhida pelo professor para tal treino.
- [x] A página deve conter uma opção onde o professor coloca quantas vezes o treino deve ser repetido.
- [x] O modal de banco de exercícios deve apresentar os exercícios de maneira mais detalhada, contendo o tempo, a carga, as repetições, as séries. ( O banco de exercícios se refere ao atributo my_exercises no back ).

**Comment by emysdias** [comment]
Acho que terminei, se quiser olhar depois @VitorLamego

**Comment by VitorLamego** [comment]
Top !! Só falta a questão da pontuação do treino que o professor precisa colocar. Mas vou fechar a issue considerando que a tela em si está completa, só não esqueçam de acrescentar isso ai. Valeuu
