### ISSUE TITLE
Pesquisa de bibliotecas de análise de dados e gráficos

### ISSUE THREAD

**Issue by VitorLamego** [OrcestraGamificacao/Dorime-Docs#30]
- [x] Pesquisar bibliotecas que trabalhem com gráficos para que possamos utilizar na aplicação web para o professor acompanhar os resultados dos seus alunos de forma gráfica.
- [x] Estudar como funciona a implementação de tais bibliotecas.

**Comment by emysdias** [comment]
Bibliotecas: 

- Google Charts (gratuita) interessante
- Recharts
- Chart.js (gratuita) interessante, mas o apexcharts parece mais
- HighCharts JS (paga)
- FusionCharts (paga)
- dc.js (gratuita)
- APEXCHARTS (gratuita)  interessante
- d3.js (gratuita) tem limitações

**Comment by emysdias** [comment]
@Sabanai104 depois ce da uma olhada também, mas gostei mais do google charts e do apexcharts

**Comment by emysdias** [comment]
https://react-google-charts.com/
